; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes='inferattrs,alloc-token<mode=typesitehashpointersplit>' -alloc-token-max=100 -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

declare ptr @malloc(i64)

define void @test_typesitehashpointersplit() sanitize_alloc_token {
; CHECK-LABEL: define void @test_typesitehashpointersplit(
; CHECK: call ptr @__alloc_token_malloc(i64 4, i64 39)
; CHECK: call ptr @__alloc_token_malloc(i64 4, i64 22)
; CHECK: call ptr @__alloc_token_malloc(i64 8, i64 56)
; CHECK: call ptr @__alloc_token_malloc(i64 4, i64 5)
; CHECK: call ptr @__alloc_token_malloc(i64 4, i64 0)
; CHECK: call ptr @__alloc_token_malloc(i64 4, i64 0)
entry:
  call ptr @malloc(i64 4), !alloc_token !0
  call ptr @malloc(i64 4), !alloc_token !1
  call ptr @malloc(i64 8), !alloc_token !2
  call ptr @malloc(i64 4), !alloc_token !3
  call ptr @malloc(i64 4), !alloc_token !4
  call ptr @malloc(i64 4)
  ret void
}

!0 = !{!"int", i1 false, !"a.cc:10:3"}
!1 = !{!"int", i1 false, !"a.cc:20:3"}
!2 = !{!"int *", i1 true, !"a.cc:30:3"}
!3 = !{!"int", i1 false, !"a.cc:10:3|a.cc:20:3"}
!4 = !{!"int", i1 false}
