; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes='inferattrs,alloc-token<mode=typefunchashpointersplit>' -alloc-token-max=1000 -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

declare ptr @malloc(i64)

define void @funcA() sanitize_alloc_token {
; CHECK-LABEL: define void @funcA(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @__alloc_token_malloc(i64 4, i64 285), !alloc_token [[META0:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @__alloc_token_malloc(i64 8, i64 929), !alloc_token [[META1:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  call ptr @malloc(i64 4), !alloc_token !0
  call ptr @malloc(i64 8), !alloc_token !1
  ret void
}

define void @funcB() sanitize_alloc_token {
; CHECK-LABEL: define void @funcB(
; CHECK-SAME: ) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @__alloc_token_malloc(i64 4, i64 325), !alloc_token [[META2:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @__alloc_token_malloc(i64 8, i64 905), !alloc_token [[META3:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  call ptr @malloc(i64 4), !alloc_token !2
  call ptr @malloc(i64 8), !alloc_token !3
  ret void
}

!0 = !{!"int", i1 0, !"funcA"}
!1 = !{!"int*", i1 1, !"funcA"}
!2 = !{!"int", i1 0, !"funcB"}
!3 = !{!"int*", i1 1, !"funcB"}
;.
; CHECK: [[META0]] = !{!"int", i1 false, !"funcA"}
; CHECK: [[META1]] = !{!"int*", i1 true, !"funcA"}
; CHECK: [[META2]] = !{!"int", i1 false, !"funcB"}
; CHECK: [[META3]] = !{!"int*", i1 true, !"funcB"}
;.
